"""empty message

Revision ID: a6959c0d3481
Revises: 31a6d2df05fd
Create Date: 2022-08-20 20:45:32.548413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6959c0d3481'
down_revision = '31a6d2df05fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experimentos', sa.Column('descricao', sa.Text(), nullable=True))
    op.drop_column('experimentos', 'descridao')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experimentos', sa.Column('descridao', sa.TEXT(), nullable=True))
    op.drop_column('experimentos', 'descricao')
    # ### end Alembic commands ###
